### PR TITLE
main.dart

### PR DESCRIPTION
**Pull request by 1997MarsRover**

### CODE REVIEW

**Comment by Evahns** [comment]
kindly add the model code file. @1997MarsRover

**Comment by 1997MarsRover** [comment]
am no sure which file is that Kindly specify

**Comment by 1997MarsRover** [comment]
am no sure which file is that Kindly specify

**Comment by Evahns** [comment]
in flutter flow project, the code page(</>) have two files, 
1. the UI widget file
2. The model file, named model.dart

If you can access them, share the code for model.dart

**Comment by Evahns** [comment]
flutter flow model

**Comment by 1997MarsRover** [comment]
import '/flutter_flow/flutter_flow_icon_button.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/flutter_flow/flutter_flow_widgets.dart';
import '/custom_code/actions/index.dart' as actions;
import 'start_widget.dart' show StartWidget;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

class StartModel extends FlutterFlowModel<StartWidget> {
  ///  State fields for stateful widgets in this page.

  final unfocusNode = FocusNode();
  // State field(s) for TextField widget.
  FocusNode? textFieldFocusNode;
  TextEditingController? textController;
  String? Function(BuildContext, String?)? textControllerValidator;

  /// Initialization and disposal methods.

  void initState(BuildContext context) {}

  void dispose() {
    unfocusNode.dispose();
    textFieldFocusNode?.dispose();
    textController?.dispose();
  }

  /// Action blocks are added here.

  /// Additional helper methods are added here.
}

**Comment by 1997MarsRover** [comment]
i dont have the model.dart file in my local machine

**Comment by Evahns** [comment]
okay, no probs

**Pull request closed without merging**
